$(document).ready(function() {
    $("#self-portrait").click(function(){
            $(".self-portrait").toggleClass("open");
    });
	$("#photoshop-inspiration").click(function(){
            $(".photoshop-inspiration").toggleClass("open");
    });
	$("#sketchbook").click(function(){
            $(".sketchbook").toggleClass("open");
    });
	$("#bulletinboard").click(function(){
            $(".bulletinboard").toggleClass("open");
    });
	$("#portfolio").click(function(){
            $(".portfolio").toggleClass("open");
    });
	$("#christmasflash").click(function(){
            $(".christmasflash").toggleClass("open");
    });
	$("#nacte").click(function(){
            $(".nacte").toggleClass("open");
    });
	$("#google").click(function(){
            $(".google").toggleClass("open");
    });
	$("#warhol").click(function(){
            $(".warhol").toggleClass("open");
    });
	$("#color-schemes").click(function(){
            $(".color-schemes").toggleClass("open");
    });
	$("#propaganda").click(function(){
            $(".propaganda").toggleClass("open");
    });
});
