# Site settings
title: Nicole Overman | Portfolio
email: nicole@nicoleoverman.me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nicoleoverman.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
    style: :compressed
